#!groovy

// Generated by IBM TransformationAdvisor
// Mon Apr 01 20:54:58 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'areyousafe'
    mvnCommands = '--version'
    test='false'
}